schema = "openwepp-hillslope-runfile-v1"
run_name = "perfho01-h2637-ofe19-without-ui"
unit_system = "metric"

[inputs]
soil = "/tmp/perfho01/run-dirs/h2637/p2637.sol"
management = "/tmp/perfho01/run-dirs/h2637/p2637.man"
slope = "/tmp/perfho01/run-dirs/h2637/p2637.slp"
climate = "/tmp/perfho01/run-dirs/h2637/p2637.cli"
wepp_ui = false
pmetpara = "/tmp/perfho01/run-dirs/h2637/pmetpara.txt"

[outputs]
pass = "/tmp/perfho01/outputs/h2637/H2637.hbp"
loss = "/tmp/perfho01/outputs/h2637/H2637.loss.json"
pass_parquet = "/tmp/perfho01/outputs/h2637/H2637.pass.parquet"
wat = "/tmp/perfho01/outputs/h2637/H2637.wat.parquet"
plot = "/tmp/perfho01/outputs/h2637/H2637.plot.parquet"
