//! Analytic expected-red controller controls; body intentionally absent.
use super::m1_trust_region_controller_interface::{M1TrustRegionControllerEvaluation as E,M1TrustRegionControllerEvaluator as V,M1TrustRegionStage1FaceEvent,M1_TRUST_REGION_CONTROLLER_DIMENSION as N};
const TOL:f64=1e-12;
#[derive(Clone,Copy)]enum K{O(f64),F,S,W}#[derive(Clone)]struct P;
struct X{k:K,b:[f64;N],s:[f64;N],l:[f64;N],u:[f64;N]}
impl X{fn new(k:K)->Self{let mut b=[300.0;N];let mut s=[1.0;N];let mut l=[f64::NEG_INFINITY;N];let mut u=[f64::INFINITY;N];for i in[0,1,2,6,7,8]{l[i]=263.15;u[i]=373.15;}l[12]=258.15;u[12]=373.15;l[13]=0.0;u[13]=0.1;b[3]=0.01;b[9]=0.01;b[4]=1000.0;b[10]=1000.0;b[5]=0.0;b[11]=0.0;b[13]=0.01;s[3]=0.01;s[9]=0.01;s[4]=1000.0;s[10]=1000.0;s[5]=1e-5;s[11]=1e-5;s[13]=0.001;l[5]=0.0;l[11]=0.0;Self{k,b,s,l,u}}fn z(&self,x:&[f64;N],i:usize)->f64{(x[i]-self.b[i])/self.s[i]}fn f(&self,x:&[f64;N],i:usize)->f64{let z=self.z(x,i);match(self.k,i){(K::O(c),0)=>-2.0+z+c*z*z,(K::F,0)=>-1.2+z,(K::F,1)=>-1.0+z,(K::S,5)=>2.0+z,(K::W,0)=>z-2f64.powi(-28),_=>z}}fn t(&self,x:&[f64;N],i:usize)->f64{match(self.k,i){(K::F,0)=>1.0+self.z(x,0)/2.0,(K::F,1)=>0.5,_=>1.0}}fn m(&self)->f64{if matches!(self.k,K::W){2f64.powi(-60)}else{1.0}}}
impl V for X{type Error=&'static str;type Payload=P;type Phase=();fn initial_coordinates(&self)->[f64;N]{self.b}fn coordinate_scales(&self)->[f64;N]{self.s}fn coordinate_bounds(&self)->[[f64;N];2]{[self.l,self.u]}fn evaluate(&mut self,x:[f64;N])->Result<E<P>,Self::Error>{Ok(E{coordinates:x,raw_residual:std::array::from_fn(|i|self.m()*self.f(&x,i)),dynamic_normalizers:std::array::from_fn(|i|self.t(&x,i)),wet_temperature_k:[300.0;2],hydraulic_potential:[0.0;4],beta:[0.5;4],ci_pa:[20.0;4],payload:P})}fn raw_jacobian(&mut self,e:&E<P>)->Result<[[f64;N];N],Self::Error>{Ok(std::array::from_fn(|i|std::array::from_fn(|j|if i==j{self.m()*match(self.k,i){(K::O(c),0)=>(1.0+2.0*c*self.z(&e.coordinates,0))/self.s[0],_=>1.0/self.s[i]}}else{0.0})))}fn select_phase(&mut self,_:&E<P>,_:[f64;N])->Result<(),Self::Error>{Ok(())}fn selected_side_probe(&mut self,_:&(),_:[f64;N])->Result<(),Self::Error>{Ok(())}fn materialize(&mut self,_:&E<P>)->Result<P,Self::Error>{Ok(P)}}
fn c(a:f64,b:f64){assert!((a-b).abs()<=TOL)}
#[test]fn ordinary(){for(k,a,r,i,d)in[(0.0,1.5,1.0,true,2.0),(-0.5,0.875,7.0/12.0,true,1.0),(-0.875,31.0/128.0,31.0/192.0,true,0.25),(-1.0,0.0,0.0,false,0.25)]{let mut x=X::new(K::O(k));let t=super::m1_trust_region_controller_transition_for_test(&mut x).unwrap();c(t.scaled_step[0],1.0);c(t.lambda,1.0);c(t.predicted_reduction,1.5);c(t.actual_reduction,a);c(t.rho,r);assert_eq!(t.installed,i);assert_eq!(t.next_radius.to_bits(),d.to_bits());assert_eq!(t.entered_materializations,0);}}
#[test]fn frozen_stationary_full_and_guard(){let mut x=X::new(K::F);let t=super::m1_trust_region_controller_transition_for_test(&mut x).unwrap();c(t.scaled_step[0],0.6);c(t.scaled_step[1],0.8);c(t.weighted_jacobian[0][0],1.0);c(t.weighted_jacobian[1][1],2.0);c(t.predicted_reduction,123.0/50.0);c(t.actual_reduction,123.0/50.0);c(t.moving_merit,788.0/4225.0);c(t.dynamic_max_normalized_residual,6.0/13.0);let mut s=X::new(K::S);let q=super::m1_trust_region_controller_transition_for_test(&mut s).unwrap();c(q.weighted_jacobian[5][5],1.0);c(q.kkt_gradient[5],2.0);c(q.kkt_normal_gradient[5],2.0);assert_eq!(q.stage1_face_events,vec![M1TrustRegionStage1FaceEvent::Free,M1TrustRegionStage1FaceEvent::LowerActivated(5),M1TrustRegionStage1FaceEvent::FreeColumns(20)]);let mut w=X::new(K::W);let b=w.b;assert_eq!(w.evaluate(b).unwrap().raw_residual[0].to_bits(),(-2f64.powi(-88)).to_bits());let r=super::m1_trust_region_controller_run_for_test(&mut w).unwrap();assert_eq!(r.initial_radius.to_bits(),1.0f64.to_bits());assert_eq!((r.proposals,r.accepted_updates,r.entered_materializations),(1,0,1));assert_eq!(r.materialized_coordinates.map(f64::to_bits),b.map(f64::to_bits));}
