use std::path::{Component, Path};

use serde::Serialize;

use crate::engine::Bundle;
use crate::error::{AssuranceError, Result};
use crate::model::{Catalog, EvidenceEntry, Lifecycle, VerificationObligation};

pub(crate) const GENERATED_MARKER: &str = "Generated by openwepp-assurance; DO NOT EDIT";

pub(crate) fn render_index(
    template: &str,
    catalog: &Catalog,
    bundles: &[Bundle],
) -> Result<String> {
    let rows = bundles
        .iter()
        .map(|bundle| {
            format!(
                "- [{}]({}) — `{}` / `{}` as of {}; \
                 [method]({}) and [model narrative]({}).",
                bundle.dossier.title,
                relative_link(&catalog.shared_outputs.index, &bundle.entry.outputs.dossier),
                bundle.dossier.lifecycle.label(),
                bundle.dossier.empirical.label(),
                bundle.dossier.evidence_as_of,
                relative_link(&catalog.shared_outputs.index, &bundle.entry.outputs.method),
                relative_link(
                    &catalog.shared_outputs.index,
                    &Path::new("usersum").join(&bundle.dossier.narrative.path)
                )
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    replace_template(template, &[(&"DOSSIER_ROWS", rows)])
}

pub(crate) fn render_method(template: &str, bundle: &Bundle) -> Result<String> {
    let values = vec![
        ("SOURCE_PATH", bundle.entry.method.display().to_string()),
        ("TITLE", bundle.method.title.clone()),
        ("METHOD_ID", bundle.method.method_id.clone()),
        ("VERSION", bundle.method.version.clone()),
        ("DESIGN", bundle.method.design.label().to_owned()),
        ("OWNER", bundle.method.owner.clone()),
        ("QUESTION", bundle.method.question.clone()),
        ("QUANTITIES", bullets(&bundle.method.quantities)),
        ("DOMAIN", bullets(&bundle.method.domain)),
        ("DATASETS", bullets(&bundle.method.datasets)),
        ("METRICS", bullets(&bundle.method.metrics)),
        ("CRITERIA", bullets(&bundle.method.criteria)),
        ("UNCERTAINTY", bullets(&bundle.method.uncertainty)),
        ("REPRODUCTION", bullets(&bundle.method.reproduction)),
        (
            "DOSSIER_LINK",
            relative_link(&bundle.entry.outputs.method, &bundle.entry.outputs.dossier),
        ),
    ];
    replace_template(template, &values)
}

pub(crate) fn render_dossier(template: &str, bundle: &Bundle) -> Result<String> {
    let narrative_path = Path::new("usersum").join(&bundle.dossier.narrative.path);
    let values = vec![
        ("SOURCE_PATH", bundle.entry.source.display().to_string()),
        ("TITLE", bundle.dossier.title.clone()),
        ("DOSSIER_ID", bundle.dossier.dossier_id.clone()),
        ("VERSION", bundle.dossier.version.clone()),
        ("LIFECYCLE", bundle.dossier.lifecycle.label().to_owned()),
        ("EVIDENCE_AS_OF", bundle.dossier.evidence_as_of.clone()),
        ("ASSESSMENT_OWNER", bundle.dossier.assessment_owner.clone()),
        ("SOURCE_IDENTITY", bundle.dossier.source_identity.clone()),
        (
            "VERIFICATION",
            bundle.dossier.verification.label().to_owned(),
        ),
        (
            "VERIFICATION_OBLIGATIONS",
            verification_table(&bundle.dossier.verification_obligations),
        ),
        ("EMPIRICAL", bundle.dossier.empirical.label().to_owned()),
        ("QUESTION", bundle.dossier.question.clone()),
        ("QUANTITIES", bullets(&bundle.dossier.quantities)),
        ("SUMMARY", bundle.dossier.summary.clone()),
        ("APPLIES_TO", bullets(&bundle.dossier.applies_to)),
        ("UNKNOWNS", bullets(&bundle.dossier.unknowns)),
        ("TESTED_DOMAIN", bullets(&bundle.dossier.tested_domain)),
        ("INTERPRETATION", bundle.interpretation.clone()),
        ("LIMITATIONS", bundle.limitations.clone()),
        (
            "APPLICATION_BOUNDARY",
            bundle.dossier.application_boundary.clone(),
        ),
        (
            "NARRATIVE_LINK",
            relative_link(&bundle.entry.outputs.dossier, &narrative_path),
        ),
        (
            "METHOD_LINK",
            relative_link(&bundle.entry.outputs.dossier, &bundle.entry.outputs.method),
        ),
        (
            "APPLICATION_WORKSHEET_LINK",
            format!(
                "[application-context worksheet]({})",
                relative_link(
                    &bundle.entry.outputs.dossier,
                    Path::new("usersum/assurance/application-context-worksheet.md")
                )
            ),
        ),
        ("EVIDENCE_PATH", bundle.entry.evidence.display().to_string()),
        ("REVIEW_PATH", bundle.entry.review.display().to_string()),
        (
            "AUTHORING_PATH",
            bundle.entry.authoring.display().to_string(),
        ),
        (
            "AUTHORING_RECORD",
            crate::authoring::authoring_markdown(&bundle.authoring),
        ),
        ("SCIENTIFIC_ROOT_SHA256", bundle.scientific_root.clone()),
        ("SOURCE_ROOT_SHA256", bundle.source_root.clone()),
        ("EVIDENCE_ROWS", evidence_table(&bundle.evidence.entries)),
        (
            "REVIEW_RECORDS",
            crate::review::review_markdown(&bundle.review),
        ),
    ];
    replace_template(template, &values)
}

pub(crate) fn render_worksheet(template: &str) -> Result<String> {
    replace_template(
        template,
        &[(
            &"ASSURANCE_CATALOG_LINK",
            "the [scientific assurance catalog](README.md)".to_owned(),
        )],
    )
}

pub(crate) fn render_export(catalog: &Catalog, bundles: &[Bundle]) -> Result<String> {
    let mut documents = vec![
        export_document(
            "vendor.openwepp.assurance.index",
            "assurance/README.md",
            "Scientific Assurance Catalog",
            "assurance.index",
            "active",
            "not_applicable",
        ),
        export_document(
            "vendor.openwepp.assurance.application_context",
            "assurance/application-context-worksheet.md",
            "Application-Context Worksheet",
            "assurance.application_context",
            "active",
            "not_applicable",
        ),
    ];
    for bundle in bundles {
        let status = downstream_status(bundle.dossier.lifecycle);
        let lifecycle = bundle.dossier.lifecycle.label().to_ascii_lowercase();
        documents.push(export_document(
            &format!(
                "vendor.openwepp.assurance.method.{}",
                bundle.method.method_id
            ),
            &strip_usersum(&bundle.entry.outputs.method)?,
            &bundle.method.title,
            &format!("assurance.method.{}", bundle.method.method_id),
            status,
            &lifecycle,
        ));
        documents.push(export_document(
            &format!(
                "vendor.openwepp.assurance.dossier.{}",
                bundle.dossier.dossier_id
            ),
            &strip_usersum(&bundle.entry.outputs.dossier)?,
            &bundle.dossier.title,
            &format!("assurance.dossier.{}", bundle.dossier.dossier_id),
            status,
            &lifecycle,
        ));
        documents.push(export_document(
            &bundle.dossier.narrative.doc_id,
            &bundle.dossier.narrative.path.to_string_lossy(),
            &bundle.dossier.narrative.title,
            &bundle.dossier.narrative.nav_key,
            status,
            &lifecycle,
        ));
    }
    documents.sort_by(|left, right| left.doc_id.cmp(&right.doc_id));
    let export = ExportFragment {
        schema_version: catalog.schema_version,
        vendor_id: "openwepp",
        documents,
    };
    let yaml = serde_yaml::to_string(&export).map_err(|error| {
        AssuranceError::Invalid(format!("failed to serialize wepppy export: {error}"))
    })?;
    let output = format!("# {GENERATED_MARKER}. Source: assurance/catalog.yaml\n{yaml}");
    crate::publication::validate_export(&output)?;
    Ok(output)
}

fn replace_template(template: &str, values: &[(impl AsRef<str>, String)]) -> Result<String> {
    if values
        .iter()
        .any(|(_, value)| value.contains('{') || value.contains('}'))
    {
        return Err(AssuranceError::Invalid(
            "template replacement value contains forbidden brace syntax".to_owned(),
        ));
    }
    let mut rendered = template.to_owned();
    for (key, value) in values {
        rendered = rendered.replace(&format!("{{{{{}}}}}", key.as_ref()), value);
    }
    verify_rendered(rendered)
}

fn verify_rendered(rendered: String) -> Result<String> {
    if rendered.contains("{{") || rendered.contains("}}") {
        return Err(AssuranceError::Invalid(
            "generated Markdown contains an unresolved template token".to_owned(),
        ));
    }
    if !rendered.contains(GENERATED_MARKER) {
        return Err(AssuranceError::Invalid(
            "generated Markdown is missing its source banner".to_owned(),
        ));
    }
    Ok(ensure_newline(rendered))
}

fn bullets(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("- {value}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn evidence_table(entries: &[EvidenceEntry]) -> String {
    let mut rows = vec![
        "| Evidence ID | Class | Forcing | Availability | Claim-bearing | Role and note |"
            .to_owned(),
        "| --- | --- | --- | --- | --- | --- |".to_owned(),
    ];
    rows.extend(entries.iter().map(|entry| {
        format!(
            "| `{}` | {} | {} | {} | {} | {} {} |",
            entry.evidence_id,
            entry.kind.label(),
            entry.forcing.label(),
            entry.availability.label(),
            entry.claim_bearing,
            entry.role.replace('|', "\\|"),
            entry.note.replace('|', "\\|")
        )
    }));
    rows.join("\n")
}

fn verification_table(obligations: &[VerificationObligation]) -> String {
    let mut rows = vec![
        "| Obligation | Mandatory | Status | Exact realization and date | Requirement / tolerance | Result | Evidence |".to_owned(),
        "| --- | --- | --- | --- | --- | --- | --- |".to_owned(),
    ];
    rows.extend(obligations.iter().map(|obligation| {
        let date = obligation.executed_on.as_deref().unwrap_or("not run");
        format!(
            "| `{}` — {} | {} | `{}` | {} ({}) | {} / {} | {} | {} |",
            obligation.obligation_id,
            table_text(&obligation.title),
            obligation.mandatory,
            obligation.status.label(),
            table_text(&obligation.realization),
            date,
            table_text(&obligation.requirement),
            table_text(&obligation.tolerance),
            table_text(&obligation.result),
            obligation
                .evidence_ids
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        )
    }));
    rows.join("\n")
}

fn relative_link(from_file: &Path, to_file: &Path) -> String {
    let mut from = normal_components(from_file);
    let to = normal_components(to_file);
    from.pop();
    let common = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();
    let mut relative = vec!["..".to_owned(); from.len().saturating_sub(common)];
    relative.extend(to.into_iter().skip(common));
    relative.join("/")
}

fn normal_components(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy().into_owned()),
            _ => None,
        })
        .collect()
}

fn strip_usersum(path: &Path) -> Result<String> {
    path.strip_prefix("usersum")
        .map(|relative| relative.to_string_lossy().into_owned())
        .map_err(|_| {
            AssuranceError::Invalid(format!(
                "wepppy export path is not under usersum: {}",
                path.display()
            ))
        })
}

fn ensure_newline(mut value: String) -> String {
    if !value.ends_with('\n') {
        value.push('\n');
    }
    value
}

#[derive(Serialize)]
struct ExportFragment {
    schema_version: u32,
    vendor_id: &'static str,
    documents: Vec<ExportDocument>,
}

#[derive(Serialize)]
struct ExportDocument {
    doc_id: String,
    source: &'static str,
    vendor_id: &'static str,
    rel_path: String,
    title: String,
    min_role: &'static str,
    category: &'static str,
    audience_tags: Vec<&'static str>,
    status: String,
    assurance_lifecycle: String,
    nav_key: String,
}

fn export_document(
    doc_id: &str,
    rel_path: &str,
    title: &str,
    nav_key: &str,
    status: &str,
    assurance_lifecycle: &str,
) -> ExportDocument {
    ExportDocument {
        doc_id: doc_id.to_owned(),
        source: "vendor",
        vendor_id: "openwepp",
        rel_path: rel_path.to_owned(),
        title: title.to_owned(),
        min_role: "user",
        category: "scientific-assurance",
        audience_tags: vec![
            "hydrologist",
            "soil-scientist",
            "researcher",
            "practitioner",
        ],
        status: status.to_owned(),
        assurance_lifecycle: assurance_lifecycle.to_owned(),
        nav_key: nav_key.to_owned(),
    }
}

fn downstream_status(lifecycle: Lifecycle) -> &'static str {
    match lifecycle {
        Lifecycle::Draft => "draft",
        Lifecycle::Candidate | Lifecycle::Published => "active",
        Lifecycle::Superseded | Lifecycle::Withdrawn => "deprecated",
    }
}

fn table_text(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::downstream_status;
    use crate::model::Lifecycle;

    #[test]
    fn downstream_status_maps_every_assurance_lifecycle() {
        assert_eq!(downstream_status(Lifecycle::Draft), "draft");
        assert_eq!(downstream_status(Lifecycle::Candidate), "active");
        assert_eq!(downstream_status(Lifecycle::Published), "active");
        assert_eq!(downstream_status(Lifecycle::Superseded), "deprecated");
        assert_eq!(downstream_status(Lifecycle::Withdrawn), "deprecated");
    }
}
