#![allow(clippy::missing_errors_doc)]

pub mod runtime_inputs;

mod constants;
mod direct_runtime;
mod hydrology;
mod winter_column;

#[cfg(test)]
mod tests;

use openwepp_kernel_contract::{HillslopeProductionFluxSymbol, HillslopeProductionStateSymbol};

pub use direct_runtime::{
    DIRECT_PHASE_COUNT, DIRECT_R3A_INPUT_ACCOUNTING_SPAN, DIRECT_R3A_PHASE_SPAN_COUNT,
    DIRECT_R3B_PHASE_SPAN_COUNT, DIRECT_R3B_WATER_LEDGER_SPAN, DIRECT_R3C_LANE_TRANSFER_SPAN,
    DIRECT_R3C_PHASE_SPAN_COUNT, DIRECT_R4A_PHASE_SPAN_COUNT, DIRECT_R4A_RUNOFF_PARTITION_SPAN,
    DIRECT_R4B_PHASE_SPAN_COUNT, DIRECT_R4B_STORAGE_RECONCILIATION_SPAN,
    DIRECT_R4C_PHASE_SPAN_COUNT, DIRECT_R4C_STORAGE_INPUT_SPAN, DIRECT_R4D_DEEP_SEEPAGE_SPAN,
    DIRECT_R4D_PHASE_SPAN_COUNT, DIRECT_R4E_PHASE_SPAN_COUNT, DIRECT_R4E_SUBSURFACE_LOSS_SPAN,
    DIRECT_R4F_EVAPOTRANSPIRATION_SPAN, DIRECT_R4F_PHASE_SPAN_COUNT, DIRECT_R4G_PHASE_SPAN_COUNT,
    DIRECT_R4G_SNOW_COUPLING_SPAN, DIRECT_R4I_LIQUID_INPUT_SPAN, DIRECT_R4I_PHASE_SPAN_COUNT,
    DIRECT_R4J_PHASE_SPAN_COUNT, DIRECT_R4J_RUNON_CARRY_SPAN,
    DIRECT_R4K_INFILTRATION_DEPRESSION_SPAN, DIRECT_R4K_PHASE_SPAN_COUNT,
    DIRECT_R4L_PHASE_SPAN_COUNT, DIRECT_R4L_SATURATION_ADDBACK_SPAN, DIRECT_R4M_PERCOLATION_SPAN,
    DIRECT_R4M_PHASE_SPAN_COUNT, DIRECT_R4N_PHASE_SPAN_COUNT, DIRECT_R4N_ROOT_PHASE_SPAN_COUNT,
    DIRECT_R4N_ROOT_UPTAKE_SPAN, DIRECT_R4N_SURFACE_ET_SPAN, DIRECT_R4N_SURFACE_PHASE_SPAN_COUNT,
    DIRECT_R4O_PHASE_SPAN_COUNT, DIRECT_R4O_SUBSURFACE_SPAN,
    DIRECT_R4PQZ_HYDROLOGY_PROJECTION_SPAN, DIRECT_R4PQZ_PHASE_SPAN_COUNT,
    DIRECT_R5B_NORMALIZATION_PHASE_SPAN_COUNT, DIRECT_R5B_NORMALIZATION_SPAN,
    DIRECT_R5B_STORAGE_BOUNDS_PHASE_SPAN_COUNT, DIRECT_R5B_STORAGE_BOUNDS_SPAN,
    DIRECT_R5C_DECOMPOSITION_PHASE_SPAN_COUNT, DIRECT_R5C_DECOMPOSITION_SPAN,
    DIRECT_R5C_RESIDUE_PARTITION_PHASE_SPAN_COUNT, DIRECT_R5C_RESIDUE_PARTITION_SPAN,
    DIRECT_R5D_ANNUAL_GROWTH_PHASE_SPAN_COUNT, DIRECT_R5D_ANNUAL_GROWTH_SPAN,
    DIRECT_R5D_PERENNIAL_GROWTH_PHASE_SPAN_COUNT, DIRECT_R5D_PERENNIAL_GROWTH_SPAN,
    DIRECT_R7D6_EROSION_PHASE_SPAN_COUNT, DIRECT_R7D6_EROSION_SPAN,
    DIRECT_R7D6_PEAK_RUNOFF_PHASE_SPAN_COUNT, DIRECT_R7D6_PEAK_RUNOFF_SPAN,
    DIRECT_TRANSFER_HOUR_COUNT, DirectCanopyInterceptionInputs, DirectCanopyInterceptionState,
    DirectDayConstructorInputs, DirectDayForcing, DirectDayFrame, DirectDecompositionAction,
    DirectDecompositionActiveContext, DirectDecompositionDownstreamOperands,
    DirectDecompositionInputs, DirectDecompositionShadowProjection, DirectDecompositionSpanReport,
    DirectDecompositionState, DirectDeepSeepageDownstreamOperands, DirectDeepSeepageInputs,
    DirectDeepSeepageShadowProjection, DirectDeepSeepageSpanReport, DirectDeepSeepageState,
    DirectDownstreamOperands, DirectErod13Inputs, DirectErod13State, DirectErod14ClassInputs,
    DirectErod14ClassState, DirectErod14Inputs, DirectErod14State, DirectErosionDownstreamOperands,
    DirectErosionInputs, DirectErosionShadowProjection, DirectErosionSpanReport,
    DirectErosionState, DirectEvapotranspirationComputeDownstreamOperands,
    DirectEvapotranspirationComputeInputs, DirectEvapotranspirationComputeShadowProjection,
    DirectEvapotranspirationComputeSpanReport, DirectEvapotranspirationComputeState,
    DirectEvapotranspirationDownstreamOperands, DirectEvapotranspirationInputs,
    DirectEvapotranspirationPmetComputeInputs, DirectEvapotranspirationPmetInputs,
    DirectEvapotranspirationShadowProjection, DirectEvapotranspirationSpanReport,
    DirectEvapotranspirationStageState, DirectEvapotranspirationState,
    DirectEvapotranspirationSurfaceDownstreamOperands,
    DirectEvapotranspirationSurfaceShadowProjection, DirectEvapotranspirationSurfaceSpanReport,
    DirectEvapotranspirationSurfaceState, DirectEvapotranspirationTraceEvent,
    DirectExecutionReport, DirectExecutorMode, DirectFrameExecutor, DirectFrostFineLayerCarry,
    DirectFrostLayerCarryProjection, DirectFrostLayerShadowCarry, DirectFrostRuntimeCarry,
    DirectGrowthAction, DirectGrowthActiveContext, DirectGrowthDownstreamOperands,
    DirectGrowthInputs, DirectGrowthShadowProjection, DirectGrowthSpanReport, DirectGrowthState,
    DirectGrowthStateSurface, DirectHydrologyProjectionDownstreamOperands,
    DirectHydrologyProjectionInputs, DirectHydrologyProjectionShadowProjection,
    DirectHydrologyProjectionSpanReport, DirectHydrologyProjectionState,
    DirectInfiltrationDepressionDownstreamOperands, DirectInfiltrationDepressionInputs,
    DirectInfiltrationDepressionShadowProjection, DirectInfiltrationDepressionSpanReport,
    DirectInfiltrationDepressionState, DirectInputAccountingState, DirectLaneConstructorInputs,
    DirectLaneFrame, DirectLaneTransferLedger, DirectLedgerDownstreamOperands,
    DirectLedgerShadowProjection, DirectLedgerSpanReport, DirectLiquidInputDownstreamOperands,
    DirectLiquidInputInputs, DirectLiquidInputShadowProjection, DirectLiquidInputSpanReport,
    DirectLiquidInputState, DirectNormalizationDownstreamOperands, DirectNormalizationInputs,
    DirectNormalizationShadowProjection, DirectNormalizationSpanReport, DirectNormalizationState,
    DirectPeakRunoffDownstreamOperands, DirectPeakRunoffInputs, DirectPeakRunoffShadowProjection,
    DirectPeakRunoffSpanReport, DirectPeakRunoffState, DirectPercolationDownstreamOperands,
    DirectPercolationInputs, DirectPercolationShadowProjection, DirectPercolationSpanReport,
    DirectPercolationState, DirectPercolationTraceEvent, DirectPhaseKind,
    DirectPhaseLifecycleStatus, DirectPhasePlan, DirectPhaseSpanReport, DirectPhaseStatusCount,
    DirectPhaseView, DirectPublicationCalendarDay, DirectPublicationClimateOperands,
    DirectPublicationDayInput, DirectPublicationDayRow, DirectPublicationErosionOperands,
    DirectPublicationEvaporationOperands, DirectPublicationExecution, DirectPublicationFrame,
    DirectPublicationInterceptionOperands, DirectPublicationLiquidInputOperands,
    DirectPublicationProfileOperands, DirectPublicationRunMetadata,
    DirectPublicationRunoffOperands, DirectPublicationStorageOperands,
    DirectPublicationSubsurfaceOperands, DirectPublicationTransferOperands,
    DirectPublicationWaterTemperatureOperands, DirectResiduePartitionDownstreamOperands,
    DirectResiduePartitionInputs, DirectResiduePartitionShadowProjection,
    DirectResiduePartitionSpanReport, DirectResiduePartitionState, DirectRunConstructorInputs,
    DirectRunFrame, DirectRunIdentity, DirectRunPublicationFrame,
    DirectRunTransferDownstreamOperands, DirectRunTransferShadowProjection,
    DirectRunTransferSpanReport, DirectRunoffDownstreamOperands, DirectRunoffPartitionInputs,
    DirectRunoffPartitionSpanReport, DirectRunoffPartitionState, DirectRunoffRebalanceTraceEvent,
    DirectRunoffShadowProjection, DirectRunonCarryDownstreamOperands, DirectRunonCarryInputs,
    DirectRunonCarryShadowProjection, DirectRunonCarrySpanReport, DirectRunonCarryState,
    DirectRuntimeAuditSnapshot, DirectRuntimeError, DirectSaturationAddbackDownstreamOperands,
    DirectSaturationAddbackInputs, DirectSaturationAddbackShadowProjection,
    DirectSaturationAddbackSpanReport, DirectSaturationAddbackState, DirectShadowProjection,
    DirectSnowCouplingDownstreamOperands, DirectSnowCouplingInputs,
    DirectSnowCouplingShadowProjection, DirectSnowCouplingSpanReport, DirectSnowCouplingState,
    DirectSnowRuntimeCarry, DirectStorageBoundsDownstreamOperands, DirectStorageBoundsInputs,
    DirectStorageBoundsShadowProjection, DirectStorageBoundsSpanReport, DirectStorageBoundsState,
    DirectStorageDownstreamOperands, DirectStorageInputDownstreamOperands,
    DirectStorageInputInputs, DirectStorageInputShadowProjection, DirectStorageInputSpanReport,
    DirectStorageInputState, DirectStorageReconciliationInputs,
    DirectStorageReconciliationSpanReport, DirectStorageReconciliationState,
    DirectStorageShadowProjection, DirectStreamingPublicationExecution,
    DirectSubsurfaceComputeDownstreamOperands, DirectSubsurfaceComputeInputs,
    DirectSubsurfaceComputeShadowProjection, DirectSubsurfaceComputeSpanReport,
    DirectSubsurfaceComputeState, DirectSubsurfaceLayerInputs, DirectSubsurfaceLayerState,
    DirectSubsurfaceLossDownstreamOperands, DirectSubsurfaceLossInputs,
    DirectSubsurfaceLossShadowProjection, DirectSubsurfaceLossSpanReport,
    DirectSubsurfaceLossState, DirectSubsurfaceSaturationTraceEvent, DirectTransferBuffers,
    DirectWaterLedgerState, DirectWaterState, DirectWb14HyetographInterval,
    DirectWb14InfiltrationProducerInputs, compute_direct_canopy_interception,
    direct_runtime_audit_snapshot, record_direct_runtime_compatibility_edge_invocation,
    reset_direct_runtime_audit_counters,
};
pub use hydrology::{
    DirectActiveFrostPartitionInputs, DirectActiveSnowPartitionInputs, DirectFrostControlInputs,
    DirectFrostFineLayerProjection, DirectFrostHourlyForcing, DirectFrostLayerInput,
    DirectFrostLayerProjection, DirectFrostLayerShadowProjection, DirectFrostPriorStateInput,
    DirectFrostThermalInputs, DirectSnowHourlyForcing, DirectSnowLiquidPartition,
    DirectSnowStage3Diagnostics, DirectWinterFrostComputeInputs, DirectWinterFrostPartitionOutcome,
    FrostSeasonalTemperatureCurve, STURM1995_CDM_CRITICAL_TEMPERATURE_C,
    STURM1995_EPHEMERAL_CDM_THRESHOLD_C_MONTH, STURM1995_HIGH_LOW_CDM_THRESHOLD_C_MONTH,
    STURM1995_HIGH_PRECIP_SPR_THRESHOLD_MM_DAY, STURM1995_HIGH_WIND_MIN_M_S,
    STURM1995_LOW_WIND_MAX_M_S, SnowAlbedoError, SnowAlbedoModel, SnowAlbedoState,
    SnowAlbedoUpdateInputs, SnowAlbedoUpdateOutcome, SnowClimateClass,
    SnowDensityCompactionConstants, SnowDensityError, SnowDensityModel, SnowDensityRuntimeInputs,
    SnowDensityRuntimeOutcome, SnowMeltModel, SnowStage3LiquidRoutingModel,
    Sturm1995ClimateClassAssignmentError, Sturm1995ClimateNormals, Sturm2010DensityParameters,
    Wb11HydrologyKernel, Wb11HydrologyKernelGuardError, snow_density_compaction_v1_constants,
    snow_density_shallow_guard_v1_constants, snow_density_spring_densification_v1_constants,
    sturm1995_climate_class_from_normals, sturm2010_bulk_density_kg_m3,
    sturm2010_density_parameters_for_class, update_snow_albedo_state,
    update_snow_density_runtime_state,
};
pub use runtime_inputs::{
    DIRECT_WINTER_HOURLY_FORCING_COUNT, DirectWinterHourlyContext, DirectWinterHourlyForcing,
    SnowPhasePartitionModel,
};
pub use winter_column::{
    DIRECT_WINTER_HOURS_PER_DAY, DirectFrostFineLayerState, DirectFrostLaneState,
    DirectFrostLayerShadowState, DirectSnowLaneState, DirectSnowLayerState,
    DirectWinterColumnState, DirectWinterDayForcing, DirectWinterDayOutcome,
    DirectWinterFrostOutcome, DirectWinterPublicationOutcome, DirectWinterSnowOutcome,
    DirectWinterStorageOutcome,
};
