[package]
name = "openwepp-input-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = true
description = "Typed openWEPP input parser contracts for WEPP source files"

[lints]
workspace = true

[dependencies]
flate2 = "1.1.0"
openwepp-management-schema = { path = "../openwepp-management-schema", version = "0.1.0" }
