#!/usr/bin/env python3
"""Render admitted assurance reports into the tracked human-review lane."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile
import uuid


REVIEW_RELATIVE = Path("usersum/assurance/review-drafts")
BUILT_RELATIVE = Path("usersum/assurance/reports")
GENERATED_HEADER = (
    "<!-- Generated by tools/local_ci/render_assurance_review_drafts.py; "
    "DO NOT EDIT. -->"
)


class ReviewRenderError(RuntimeError):
    """A fail-closed review-rendering error."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def regular_inventory(root: Path) -> dict[str, str]:
    """Return exact relative-path/content identities for a regular tree."""
    if not root.is_dir() or root.is_symlink():
        raise ReviewRenderError(f"required regular directory is unavailable: {root}")
    inventory: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        metadata = path.lstat()
        if stat.S_ISLNK(metadata.st_mode):
            raise ReviewRenderError(f"review tree contains a symlink: {relative}")
        if stat.S_ISDIR(metadata.st_mode):
            continue
        if not stat.S_ISREG(metadata.st_mode):
            raise ReviewRenderError(f"review tree contains a special file: {relative}")
        inventory[relative] = _sha256(path)
    return inventory


def compare_inventories(
    expected: dict[str, str], observed: dict[str, str]
) -> list[str]:
    """Describe missing, extra, and content-drifted files."""
    findings: list[str] = []
    for path in sorted(expected.keys() - observed.keys()):
        findings.append(f"missing: {path}")
    for path in sorted(observed.keys() - expected.keys()):
        findings.append(f"extra: {path}")
    for path in sorted(expected.keys() & observed.keys()):
        if expected[path] != observed[path]:
            findings.append(f"drift: {path}")
    return findings


def _report_entries(reports: Path) -> list[tuple[str, str, str, str]]:
    entries: list[tuple[str, str, str, str]] = []
    for report_dir in sorted(reports.iterdir()):
        if not report_dir.is_dir() or report_dir.is_symlink():
            raise ReviewRenderError(
                f"rendered report entry is not a regular directory: {report_dir.name}"
            )
        versions = [
            path
            for path in sorted(report_dir.iterdir())
            if path.is_dir() and not path.is_symlink()
        ]
        if len(versions) != 1:
            raise ReviewRenderError(
                f"rendered report must have exactly one version: {report_dir.name}"
            )
        version_dir = versions[0]
        index_path = version_dir / "index.md"
        manifest_path = version_dir / "build-manifest.json"
        if not index_path.is_file() or index_path.is_symlink():
            raise ReviewRenderError(f"rendered report lacks index: {report_dir.name}")
        if not manifest_path.is_file() or manifest_path.is_symlink():
            raise ReviewRenderError(
                f"rendered report lacks build manifest: {report_dir.name}"
            )
        title = next(
            (
                line.removeprefix("# ").strip()
                for line in index_path.read_text(encoding="utf-8").splitlines()
                if line.startswith("# ")
            ),
            "",
        )
        if not title:
            raise ReviewRenderError(f"rendered report lacks an H1: {report_dir.name}")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        source_root = manifest.get("source_root_sha256")
        if not isinstance(source_root, str) or len(source_root) != 64:
            raise ReviewRenderError(
                f"rendered report has an invalid source root: {report_dir.name}"
            )
        entries.append((report_dir.name, version_dir.name, title, source_root))
    if not entries:
        raise ReviewRenderError("rendered report catalog is empty")
    return entries


def render_index(reports: Path) -> bytes:
    """Build the deterministic review-only catalog."""
    lines = [
        GENERATED_HEADER,
        "# Scientific Assurance Review Drafts",
        "",
        "> [!CAUTION]",
        "> These are rendered **DRAFT** reports for human review. They are not",
        "> independently approved, published, released, exported, or endorsed",
        "> for application-fitness decisions.",
        "",
        "Review the resolved manuscript, supplement, figures, limitations, and",
        "linked evidence—not the templated YAML source alone.",
        "",
        "## Rendered Drafts",
        "",
    ]
    for report_id, version, title, source_root in _report_entries(reports):
        base = f"{report_id}/{version}"
        lines.extend(
            [
                f"- [{title}]({base}/index.md)",
                f"  ([technical supplement]({base}/supplement.md))",
                f"  - Report ID: `{report_id}`",
                f"  - Source root: `{source_root}`",
            ]
        )
    lines.extend(
        [
            "",
            "The approved public report catalog remains",
            "[separate](../README.md) and may contain only reports that complete",
            "the governed human-review and release process.",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def _assert_no_symlink_components(root: Path, path: Path) -> None:
    relative = path.relative_to(root)
    current = root
    for component in relative.parts:
        current = current / component
        if current.exists() and current.is_symlink():
            raise ReviewRenderError(f"destination component is a symlink: {current}")


def _copy_usersum_without_review_drafts(source: Path, target: Path) -> None:
    regular_inventory(source)

    def ignore(directory: str, names: list[str]) -> set[str]:
        relative = Path(directory).relative_to(source)
        if relative == Path("assurance") and "review-drafts" in names:
            return {"review-drafts"}
        return set()

    shutil.copytree(source, target, copy_function=shutil.copy2, ignore=ignore)


def _run_builder(binary: Path, root: Path, stage: Path) -> None:
    for operation in ("build", "check"):
        result = subprocess.run(
            [str(binary), operation, "--all", "--staging-root", str(stage)],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            detail = result.stderr.strip() or result.stdout.strip()
            raise ReviewRenderError(
                f"assurance {operation} failed with {result.returncode}: {detail}"
            )


def _prepare_candidate(binary: Path, root: Path, stage: Path) -> Path:
    _copy_usersum_without_review_drafts(root / "usersum", stage / "usersum")
    _run_builder(binary, root, stage)
    built = stage / BUILT_RELATIVE
    regular_inventory(built)
    candidate = stage / REVIEW_RELATIVE
    shutil.copytree(built, candidate, copy_function=shutil.copy2)
    (candidate / "README.md").write_bytes(render_index(candidate))
    regular_inventory(candidate)
    return candidate


def _install_candidate(candidate: Path, destination: Path) -> str:
    expected = regular_inventory(candidate)
    if destination.exists():
        observed = regular_inventory(destination)
        if not compare_inventories(expected, observed):
            return "no-op"
    parent = destination.parent
    backup = parent / f".review-drafts.backup.{uuid.uuid4().hex}"
    if backup.exists():
        raise ReviewRenderError(f"unexpected backup collision: {backup}")
    moved_old = False
    try:
        if destination.exists():
            os.replace(destination, backup)
            moved_old = True
        os.replace(candidate, destination)
        installed = regular_inventory(destination)
        findings = compare_inventories(expected, installed)
        if findings:
            raise ReviewRenderError(
                "installed review tree failed verification: " + "; ".join(findings)
            )
    except Exception:
        if moved_old and backup.exists():
            if destination.exists():
                shutil.rmtree(destination)
            os.replace(backup, destination)
        raise
    if backup.exists():
        shutil.rmtree(backup)
    return "applied"


def execute(root: Path, binary: Path, apply: bool) -> int:
    root = root.resolve(strict=True)
    if not (root / "assurance/v2/catalog.yaml").is_file():
        raise ReviewRenderError(f"not an openWEPP repository root: {root}")
    binary = binary.resolve(strict=True)
    metadata = binary.lstat()
    if binary.is_symlink() or not stat.S_ISREG(metadata.st_mode):
        raise ReviewRenderError(f"assurance binary is not a regular file: {binary}")
    if not os.access(binary, os.X_OK):
        raise ReviewRenderError(f"assurance binary is not executable: {binary}")
    destination = root / REVIEW_RELATIVE
    _assert_no_symlink_components(root, destination)
    target = root / "target"
    target.mkdir(exist_ok=True)
    if target.is_symlink() or not target.is_dir():
        raise ReviewRenderError(f"temporary root is not a regular directory: {target}")
    with tempfile.TemporaryDirectory(
        prefix="assurance-review-render.", dir=target
    ) as temporary:
        candidate = _prepare_candidate(binary, root, Path(temporary))
        expected = regular_inventory(candidate)
        if not apply:
            if not destination.exists():
                raise ReviewRenderError(f"tracked review tree is missing: {destination}")
            findings = compare_inventories(
                expected, regular_inventory(destination)
            )
            if findings:
                raise ReviewRenderError(
                    "tracked review tree is stale: " + "; ".join(findings)
                )
            print(f"review rendering: PASS ({len(expected)} files current)")
            return 0
        result = _install_candidate(candidate, destination)
        print(f"review rendering: {result} ({len(expected)} files)")
        return 0


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--binary", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    try:
        return execute(args.root, args.binary, args.apply)
    except (OSError, ValueError, json.JSONDecodeError, ReviewRenderError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
