schema = "openwepp-hillslope-runfile-v1"
run_name = "mn_corn_h4"
unit_system = "metric"

[inputs]
soil = "p4.sol"
management = "p4.man"
slope = "p4.slp"
climate = "p4.cli"
wepp_ui = true
pmetpara = "pmetpara.txt"

[outputs]
pass = "output-hybrid/H4.hbp"
loss = "output-hybrid/H4.loss.json"
pass_parquet = "output-hybrid/H4.pass.parquet"
wat = "output-hybrid/H4.wat.parquet"
