[package]
name = "openwepp-hillslope-output"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
arrow-array = "54.3.1"
arrow-ipc = "54.3.1"
arrow-schema = "54.3.1"
base64 = "0.22.1"
flatbuffers = "24.3.25"
openwepp-sim-contract = { path = "../openwepp-sim-contract", version = "0.1.0" }
parquet = { version = "54.3.1", default-features = false, features = ["arrow", "snap"] }
