schema = "openwepp-hillslope-runfile-v1"
run_name = "r7d4-default-h2637"
unit_system = "metric"

[inputs]
soil = "/tmp/perfho01/run-dirs/h2637/p2637.sol"
management = "/tmp/perfho01/run-dirs/h2637/p2637.man"
slope = "/tmp/perfho01/run-dirs/h2637/p2637.slp"
climate = "/tmp/perfho01/run-dirs/h2637/p2637.cli"
wepp_ui = false
pmetpara = "/tmp/perfho01/run-dirs/h2637/pmetpara.txt"

[outputs]
pass = "/tmp/r7d4-h2637/default/H2637.hbp"
loss = "/tmp/r7d4-h2637/default/H2637.loss.json"
pass_parquet = "/tmp/r7d4-h2637/default/H2637.pass.parquet"
wat = "/tmp/r7d4-h2637/default/H2637.wat.parquet"
plot = "/tmp/r7d4-h2637/default/H2637.plot.parquet"
