#!/usr/bin/env python3
"""Generate the exhaustive restart field ledger from authoritative Rust structs."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs/work-packages/20260817-direct-hydrology-persisted-restart-authority-001/artifacts/direct-run-frame-field-classification.md"
TARGETS = {
    "DirectRunFrame": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/00_core_frames.rs",
    "DirectLaneFrame": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/00_core_frames.rs",
    "DirectWaterState": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/02_state_reports.rs",
    "DirectTransferBuffers": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/02_state_reports.rs",
    "DirectLaneTransferLedger": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/02_state_reports.rs",
    "DirectRunTransferDownstreamOperands": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/02_state_reports.rs",
    "DirectSubsurfaceLayerState": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/subsurface.rs",
    "DirectEvapotranspirationStageState": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/evapotranspiration.rs",
    "DirectGrowthStateSurface": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/growth.rs",
    "DirectWinterColumnState": "crates/openwepp-hillslope-orchestrator/src/winter_column.rs",
    "DirectSnowRuntimeCarry": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/00_core_frames.rs",
    "DirectFrostRuntimeCarry": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/00_core_frames.rs",
    "DirectErosionDownstreamOperands": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/erosion.rs",
    "DirectErosionInflowIntake": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/erosion_seed.rs",
    "DirectErosionRuntimeCarry": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/erosion_seed.rs",
    "DirectGroundwaterRunState": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/groundwater.rs",
    "DirectSurfaceLiquidOwnedState": "crates/openwepp-hillslope-orchestrator/src/direct_runtime/surface_liquid_owner.rs",
}


def fields(name: str, relative: str) -> list[tuple[str, str]]:
    source = (ROOT / relative).read_text()
    match = re.search(rf"pub struct {name}\s*\{{", source)
    if match is None:
        raise RuntimeError(f"missing {name}")
    body = source[match.end():]
    depth = 1
    selected = []
    for line in body.splitlines():
        depth += line.count("{") - line.count("}")
        if depth == 0:
            break
        field = re.match(r"\s*pub\s+([A-Za-z0-9_]+):\s*(.+),\s*$", line)
        if field and depth == 1:
            selected.append((field.group(1), field.group(2)))
    if not selected:
        raise RuntimeError(f"no fields parsed for {name}")
    return selected


def units(field: str, rust_type: str) -> str:
    suffixes = {
        "_kg_m2": "kg m^-2", "_kg": "kg", "_m3_s": "m^3 s^-1",
        "_m_s": "m s^-1", "_m2": "m^2", "_m": "m", "_s": "s",
        "_pa": "Pa", "_c": "degC", "_k": "K", "_j_m2": "J m^-2",
    }
    for suffix, value in suffixes.items():
        if field.endswith(suffix):
            return value
    if "bool" in rust_type:
        return "boolean"
    if any(token in rust_type for token in ("usize", "u8", "u16", "u32", "u64", "u128")):
        return "count/index or identity"
    return "dimensionless or typed by nested DTO"


def classification(owner: str, field: str) -> tuple[str, str]:
    special = {
        ("DirectRunFrame", "phase_plan"): ("reconstructed", "phase-plan configuration digest"),
        ("DirectRunFrame", "publication"): ("excluded scratch", "empty publication scratch"),
        ("DirectRunFrame", "lane_transfer_shadow_projection"): ("reconstructed", "ledger plus topology"),
        ("DirectRunFrame", "laned_active"): ("unsupported", "typed rejection before serialization"),
        ("DirectRunFrame", "laned_active_summary"): ("excluded scratch", "must be absent"),
        ("DirectLaneFrame", "publication"): ("excluded scratch", "empty publication scratch"),
        ("DirectLaneFrame", "day_inputs"): ("reconstructed immutable input", "bound day-input digest"),
    }
    return special.get((owner, field), ("persisted explicit DTO", "canonical wire field"))


lines = [
    "# Exhaustive direct-hydrology restart field classification",
    "",
    "Status: `GENERATED / authority input`",
    "",
    "Generated by `tools/restart_authority/generate_field_ledger.py` from the named",
    "authoritative Rust structs plus the mapping metadata in this generator. Source order is canonical DTO order. Production",
    "projection must destructure every listed source struct without `..`; this",
    "ledger generation is an inventory guard, not a substitute for that compile-time guard.",
    "",
]
for owner, relative in TARGETS.items():
    lines += [
        f"## `{owner}`",
        "",
        "| Source field | Rust type | Classification | Wire field | Units | Domain / validation | Reconstruction source | Poison | Consequence if omitted |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for field, rust_type in fields(owner, relative):
        kind, reconstruction = classification(owner, field)
        domain = "strict typed parse; finite/domain validation; exact identity and canonical-order checks"
        poison = "one-bit HexF64 mutation, identity mutation, order mutation, or presence mutation as applicable"
        consequence = "continuation state, custody, lineage, or deterministic reconstruction can diverge"
        lines.append(
            f"| `{field}` | `{rust_type}` | {kind} | `{field}` | {units(field, rust_type)} | "
            f"{domain} | {reconstruction} | {poison} | {consequence} |"
        )
    lines.append("")

lines += [
    "## Binding dispositions",
    "",
    "- `phase_plan` is digest-bound and deterministically reconstructed.",
    "- `publication` is excluded scratch and must be rebuilt empty; output equivalence is an implementation gate.",
    "- `lane_transfer_shadow_projection` is reconstructed and exact-checked from the persisted ledger and topology.",
    "- `day_inputs` is an immutable digest-bound input; in-progress restore uses the persisted day identity and repository reconstruction.",
    "- `laned_active` is rejected before serialization and restore.",
    "- `surface_liquid_shadow` is the sole surface-liquid state representation; the outer checkpoint binds configuration only.",
]
OUTPUT.write_text("\n".join(lines) + "\n")
