[package]
name = "openwepp-topology"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
openwepp-sim-contract = { path = "../openwepp-sim-contract", version = "0.1.0" }
