[package]
name = "openwepp-watershed-orchestrator"
version = "0.1.0"
edition = "2024"
license = "CC0-1.0"
publish = false

[workspace]

[dependencies]
openwepp-sim-contract = { path = "../openwepp-sim-contract", version = "0.1.0" }
openwepp-topology = { path = "../openwepp-topology", version = "0.1.0" }
